### PR TITLE
refactor: changed text execution to do-while loop from dataset conditionals

### PR DESCRIPTION
**Pull request by mikesaintsg**
## Proposed changes

Refactor that moves the test runner execution into a do while loop instead of being duplicated to accommodate the dataset condition

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [X] Refactor (makes code concise and improves readability)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/thetutlage/japa/blob/master/.github/CONTRIBUTING.md) doc
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by thetutlage** [comment]
What's the purpose of the change?

**Comment by mikesaintsg** [comment]
There's a bunch of conditionals based on the dataset and the test runner is duplicated because of them, even though it will be called at least once. A do while statement is made just for this to cut down on all the boilerplate code. I'm using the same on my code base, just wanted to share

**Comment by thetutlage** [comment]
Ahhh okay. Makes sense!

I appreciate you taking out time for the PR. However, I do not use `do/while` loops anywhere in my projects. So I will refrain myself from using it here as well :)

**Comment by mikesaintsg** [comment]
Not a problem, thanks for the look!

**Pull request closed without merging**
